/*******************************************************************************
 * Copyright (c) 2026 Rémi Dutil.
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License v2.0 which accompanies
 * this distribution, and is available at:
 *   https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html
 *
 * Contributors:
 *     Rémi Dutil - created for ManaDesk
 *******************************************************************************/

package com.reflexit.magiccards.core.sync;

import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.imageio.ImageIO;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public final class SymbolConverter {

	/**
	 * This map is generated by main() and pasted here manually.
	 * It maps "{G/U}" → "gu.svg" (Scryfall canonical filename).
	 */
	private static final Map<String, String> SCRYFALL_MANA = Map.ofEntries(
			// --- GENERATED TABLE START ---
			Map.entry("{1000000}", "1000000.svg"), Map.entry("{B/R/P}", "BRP.svg"), Map.entry("{R/G/P}", "RGP.svg"),
			Map.entry("{U/B/P}", "UBP.svg"), Map.entry("{B/G/P}", "BGP.svg"), Map.entry("{G/U/P}", "GUP.svg"),
			Map.entry("{W/B/P}", "WBP.svg"), Map.entry("{W/U/P}", "WUP.svg"), Map.entry("{CHAOS}", "CHAOS.svg"),
			Map.entry("{U/R/P}", "URP.svg"), Map.entry("{G/W/P}", "GWP.svg"), Map.entry("{R/W/P}", "RWP.svg"),
			Map.entry("{R/G}", "RG.svg"), Map.entry("{U/R}", "UR.svg"), Map.entry("{W/P}", "WP.svg"),
			Map.entry("{C/P}", "CP.svg"), Map.entry("{W/U}", "WU.svg"), Map.entry("{G/P}", "GP.svg"),
			Map.entry("{B/G}", "BG.svg"), Map.entry("{U/B}", "UB.svg"), Map.entry("{2/U}", "2U.svg"),
			Map.entry("{2/W}", "2W.svg"), Map.entry("{C/B}", "CB.svg"), Map.entry("{C/W}", "CW.svg"),
			Map.entry("{G/W}", "GW.svg"), Map.entry("{2/B}", "2B.svg"), Map.entry("{R/W}", "RW.svg"),
			Map.entry("{B/R}", "BR.svg"), Map.entry("{C/G}", "CG.svg"), Map.entry("{2/R}", "2R.svg"),
			Map.entry("{W/B}", "WB.svg"), Map.entry("{U/P}", "UP.svg"), Map.entry("{2/G}", "2G.svg"),
			Map.entry("{C/R}", "CR.svg"), Map.entry("{C/U}", "CU.svg"), Map.entry("{G/U}", "GU.svg"),
			Map.entry("{R/P}", "RP.svg"), Map.entry("{B/P}", "BP.svg"), Map.entry("{100}", "100.svg"),
			Map.entry("{17}", "17.svg"), Map.entry("{12}", "12.svg"), Map.entry("{20}", "20.svg"),
			Map.entry("{16}", "16.svg"), Map.entry("{TK}", "TK.svg"), Map.entry("{11}", "11.svg"),
			Map.entry("{PW}", "PW.svg"), Map.entry("{19}", "19.svg"), Map.entry("{15}", "15.svg"),
			Map.entry("{HW}", "HW.svg"), Map.entry("{10}", "10.svg"), Map.entry("{HR}", "HR.svg"),
			Map.entry("{18}", "18.svg"), Map.entry("{14}", "14.svg"), Map.entry("{13}", "13.svg"),
			Map.entry("{8}", "8.svg"), Map.entry("{U}", "U.svg"), Map.entry("{4}", "4.svg"), Map.entry("{Q}", "Q.svg"),
			Map.entry("{0}", "0.svg"), Map.entry("{E}", "E.svg"), Map.entry("{A}", "A.svg"),
			Map.entry("{½}", "HALF.svg"), Map.entry("{9}", "9.svg"), Map.entry("{Z}", "Z.svg"),
			Map.entry("{5}", "5.svg"), Map.entry("{1}", "1.svg"), Map.entry("{R}", "R.svg"), Map.entry("{B}", "B.svg"),
			Map.entry("{W}", "W.svg"), Map.entry("{6}", "6.svg"), Map.entry("{S}", "S.svg"), Map.entry("{2}", "2.svg"),
			Map.entry("{G}", "G.svg"), Map.entry("{C}", "C.svg"), Map.entry("{∞}", "INFINITY.svg"),
			Map.entry("{7}", "7.svg"), Map.entry("{X}", "X.svg"), Map.entry("{3}", "3.svg"), Map.entry("{T}", "T.svg"),
			Map.entry("{P}", "P.svg"), Map.entry("{L}", "L.svg"), Map.entry("{H}", "H.svg"), Map.entry("{D}", "D.svg"),
			Map.entry("{Y}", "Y.svg")
	// --- GENERATED TABLE END ---
	);

	private SymbolConverter() {
	}

	/** Returns the canonical Scryfall filename for a mana symbol. */
	public static String getScryfallFilename(String symbol) {
		return SCRYFALL_MANA.get(symbol);
	}

	/** Returns the Scryfall SVG URL for a mana symbol. */
	public static URL getScryfallManaURL(String symbol) {
		String file = SCRYFALL_MANA.get(symbol);
		if (file == null) {
			System.err.println("Unknown mana symbol: " + symbol);
			return null;
		}
		try {
			return new URL("https://svgs.scryfall.io/card-symbols/" + file);
		} catch (Exception e) {
			System.err.println("Invalid URL for symbol " + symbol + ": " + e.getMessage());
			return null;
		}
	}

	// =====================================================================================
	//  MAIN — Generates the SCRYFALL_MANA table AND PNGs in /tmp/symbols
	// =====================================================================================

	public static void main(String[] args) {
		try {
			String json = fetch("https://api.scryfall.com/symbology");
			if (json == null) {
				System.err.println("ERROR: Could not fetch Scryfall symbology.");
				return;
			}

			JSONParser parser = new JSONParser();
			JSONObject root = (JSONObject) parser.parse(json);
			JSONArray data = (JSONArray) root.get("data");

			if (data == null) {
				System.err.println("ERROR: Missing 'data' array in Scryfall response.");
				return;
			}

			Map<String, String> map = new HashMap<>();

			// Output directory: /tmp/symbols
			File outDir = new File(System.getProperty("java.io.tmpdir"), "symbols");
			if (!outDir.exists() && !outDir.mkdirs()) {
				System.err.println("ERROR: Could not create output directory: " + outDir);
				return;
			}
			System.out.println("PNG output directory: " + outDir.getAbsolutePath());

			for (Object o : data) {
				if (!(o instanceof JSONObject))
					continue;

				JSONObject obj = (JSONObject) o;

				String symbol = (String) obj.get("symbol");
				String svgUri = (String) obj.get("svg_uri");

				if (symbol == null || svgUri == null)
					continue;

				String file = extractFilename(svgUri);
				if (file == null)
					continue;

				map.put(symbol, file);

				// Download + convert SVG -> PNG using your SvgRasterizer
				try {
					URL url = new URL(svgUri);
					BufferedImage bi = SvgRasterizer.renderSvgPreserveColor(url, 19, 19);

					File outPng = new File(outDir, file.replace(".svg", ".png"));
					try (OutputStream out = new FileOutputStream(outPng)) {
						ImageIO.write(bi, "png", out);
					}

					System.out.println("Wrote PNG: " + outPng.getName());
				} catch (Exception e) {
					System.err.println("WARNING: Failed to convert " + svgUri + ": " + e.getMessage());
				}
			}

			// Sort by descending length (hybrids first)
			List<String> keys = new ArrayList<>(map.keySet());
			keys.sort((a, b) -> Integer.compare(b.length(), a.length()));

			// Print Java initializer
			System.out.println();
			System.out.println("=== Paste into SCRYFALL_MANA ===");
			System.out.println("Map.ofEntries(");
			for (String key : keys) {
				System.out.println("    Map.entry(\"" + key + "\", \"" + map.get(key) + "\"),");
			}
			System.out.println(");");
			System.out.println("=== Done ===");
			System.out.println("PNGs written to: " + outDir.getAbsolutePath());

		} catch (Exception e) {
			System.err.println("FATAL ERROR in SymbolConverter.main: " + e.getMessage());
			e.printStackTrace();
		}
	}

	// =====================================================================================
	//  Helpers
	// =====================================================================================

	private static String fetch(String urlStr) {
		try {
			URL url = new URL(urlStr);
			HttpURLConnection con = (HttpURLConnection) url.openConnection();
			con.setRequestProperty("User-Agent", "ManaDesk-Symbol-Generator");
			con.setConnectTimeout(10000);
			con.setReadTimeout(10000);

			if (con.getResponseCode() != 200)
				return null;

			try (BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()))) {
				StringBuilder sb = new StringBuilder();
				String line;
				while ((line = br.readLine()) != null)
					sb.append(line);
				return sb.toString();
			}
		} catch (Exception e) {
			System.err.println("ERROR fetching URL " + urlStr + ": " + e.getMessage());
			return null;
		}
	}

	private static String extractFilename(String svgUri) {
		int idx = svgUri.lastIndexOf('/');
		if (idx == -1 || idx == svgUri.length() - 1)
			return null;
		return svgUri.substring(idx + 1);
	}
}