# Contributors:
#     Rémi Dutil (20.10.526) - updated for ManaDesk creation and Eclipse 2.0 migration
source.. = src/
output.. = target/classes
bin.includes = META-INF/,\
               .,\
               lib/cglib-nodep-2.2.2.jar,\
               lib/javassist-3.18.2-GA.jar,\
               lib/junit-4.12.jar
jars.compile.order = .
